config/routes.rb
Rails.application.routes.draw do
  resources :masters
  resources :repair_orders

  get 'stock/index'

  devise_for :users
  get 'persons/profile'

  
  get 'persons/profile', as: 'user_root' # после успешного входа в систему перенаправить на страницу профиля пользователя
  root 'welcome#index'
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
	belongs_to :repair_order
end

app/models/claimer.rb
class Claimer < ApplicationRecord
	#validates 	:fio, 	presence: true, length: { maximum: 50 }
	#validates	:phone, presence: true, length: { maximum: 15 }
	#validates	:email, length: { maximum: 40 }
	#validates	:city, 	presence: true, length: { maximum: 20 }
	#validates	:adress, presence: true, length: { maximum: 60 }

	has_many :repair_orders	
	has_many :devices, :through => :repair_order
	
	#accepts_nested_attributes_for :repair_orders
	
end

app/models/device.rb
class Device < ApplicationRecord
	has_one :repair_order
end

app/models/master.rb
class Master < ApplicationRecord
	has_many :repair_orders
end

app/models/repair_order.rb
class RepairOrder < ApplicationRecord
	#validates :claimer_id, presence: true
	
	belongs_to :claimer
	belongs_to :device
	has_one :master
	has_one :status_order
	has_one :brand
	has_many :used_repair_parts

	accepts_nested_attributes_for :claimer
	accepts_nested_attributes_for :device

	def self.search(query)
  	  #where("repair_orders.master_id like ?", "%#{query}%") #search by Masters
  	  joins(:claimer).where("phone like ?", "%#{query}%") #search method by phone
	end
	
end

app/models/status_order.rb
class StatusOrder < ApplicationRecord
	belongs_to :repair_order
end

app/models/stock.rb
class Stock < ApplicationRecord
end

app/models/used_repair_part.rb
class UsedRepairPart < ApplicationRecord
	belongs_to :repair_order
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  #1. Database Authenticatable: предоставляет возможность входа в систему на основе зашифрованного и хранимого в базе данных пароля. Вход может быть выполнен посредством отправки POST-запроса или с помощью HTTP Basic Authentication.
  #2. Omniauthable: добавляет поддержку Omniauth (https://github.com/intridea/omniauth).
  #3. Confirmable: позволяет отправлять письмо с инструкциями для подтверждения аккаунта, созданного во время регистрации.
  #4. Recoverable: позволяет восстанавливать забытый пароль. Отправляет инструкции по восстановлению на почту.
  #5. Registerable: управляет регистрацией пользователей, позволяет редактировать и удалять аккаунты.
  #6. Rememberable: позволяет запоминать пользователей на основе cookies. Управляет созданием и удалением токенов.
  #7. Trackable: ведет статистику количества входов, учитывает время и IT-адреса.
  #8. Timeoutable: отвечает за продолжительность сессии активности пользователя в системе;
  #9. Validatable: предоставляет инструменты валидации e-mail и пароля. Модуль может быть легко настроен, вы можете определить собственные валидаторы.
  #10. Lockable: блокирует аккаунт после указанного в настройках количество неудачных попыток авторизации. Аккаунт может быть разблокирован посредством email или через определенный период времени.
  devise :database_authenticatable, 
  		 :registerable,
         :recoverable, 
         :rememberable, 
         :trackable, 
         :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #def after_sign_in_path_for(resource)
  #	current_user_path
  #end

  #def after_sign_out_path_for(resource_or_scope)
  #	request.referrer
 # end
  
end

app/controllers/masters_controller.rb
class MastersController < ApplicationController
  before_filter :authenticate_user!
  def new
  	@master = Master.new
  end

  def create
  	@master = Master.new(master_params)

    respond_to do |format|
      if @master.save
        format.html { redirect_to new_master_url, notice: 'Мастер был успешно добавден.' }
        format.json { render action: 'new', status: :created, location: @master }
      else
        format.html { render action: 'new' }
        format.json { render json: @master.errors, status: :unprocessable_entity }
      end
	end
  end

  def master_params
    params.require(:master).permit(:name, :category)
  end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def profile
  end
end

app/controllers/repair_orders_controller.rb
class RepairOrdersController < ApplicationController
  before_filter :authenticate_user!
  
  def index
  	@repair_orders = RepairOrder.all.reverse_order
    if params[:search]   
      @repair_orders = RepairOrder.search(params[:search]).order("created_at DESC")
    else 
      @repair_orders = RepairOrder.all.order('created_at DESC')
    end
    
  	@claimers = Claimer.all
  	@devices = Device.all
  	@masters = Master.all
    @brands = Brand.all
  end
  
  def new
    @master_options = Master.all.map{|u| [ u.name, u.id ] } #for select list
    @brand_options = Brand.all.map{|u| [ u.brand_name, u.id ] }
  	@repair_order = RepairOrder.new
    @repair_order.build_claimer
    @repair_order.build_device
  end
  
  def create
    @repair_order = RepairOrder.new(repair_order_params)

    respond_to do |format|
      if @repair_order.save
        format.html { redirect_to repair_orders_url, notice: 'Заказ успешно добавлен.' }
        format.json { render action: 'new', status: :created, location: @repair_order }
      else
        format.html { render action: 'new' }
        format.json { render json: @repair_order.errors, status: :unprocessable_entity }
      end
    end
  end

  def repair_order_params
    params.require(:repair_order).permit(:claimer_id, :master_id, :description, :type_order, :date_create,
                                         :date_complite, :date_return, :date_dead_line, :waranty_period, :date_purchase,
      claimer_attributes: [:fio, :phone, :email, :city, :adress], 
      device_attributes: [:model, :serial_number, :brand_id, :device_type, :defect, :accessories, :appearences],
      brand_attributes: [:brand_name])
  end

end

app/controllers/stock_controller.rb
class StockController < ApplicationController
  before_filter :authenticate_user!
  def index
           
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	before_filter :authenticate_user! #, except => [:show, :index]
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Service"
    full_base_title = "Service Management"
    if page_title.empty?
      full_base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/masters_helper.rb
module MastersHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/repair_orders_helper.rb
module RepairOrdersHelper

	def sec2dhms(seсs)
     time = seсs.round           # Отбрасываем микросекунды.
     sec = time % 60             # Извлекаем секунды.
     time /= 60                  # Отбрасываем секунды.
     mins = time % 60            # Извлекаем минуты.
     time /= 60                  # Отбрасываем минуты.
     hrs = time % 24             # Извлекаем часы.
     time /= 24                  # Отбрасываем часы.
     days = time                 # Дни (последний остаток).

     [days, hrs, mins, sec]      # Возвращаем массив [d,h,m,s].
    end

end

app/helpers/stock_helper.rb
module StockHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/masters/new.html.erb
<h1 align = "center">Внесение нового мастера в базу данных</h1>
<div class="row">  
    <div class="container">
      <div class="card card-container">

		<%= form_for(@master, :html => { class: "form-group" }) do |f| %>
			<div class="field">
			  <%= f.text_field :name, class: "form-control", placeholder: "Введите имя мастера" %>
			</div>
		<br>
			<div class="field"> 
			  <%= f.text_field :category, class: "form-control", placeholder: "Введите категорию мастера" %>
			</div>
		<br>
			<div class="actions">
		      <%= f.submit "Добавить мастера", class: "btn btn-lg btn-primary btn-block btn-signin" %>
			</div>
		<% end %>
		<%= link_to 'Вернутся на главную', root_url%>
	  </div><!-- /card-container -->
	</div><!-- /container -->      
</div>

app/views/persons/profile.html.erb
<% provide(:title, 'Owner') %>

<h1>Страница пользователя</h1>
	<% if user_signed_in? %>
	        <span>Здравствуйте, <span class="email-style"><%= current_user.email %></span></span>
	        <%= link_to 'Выйти', destroy_user_session_path, :method => :delete, class: "btn btn-default" %>
	    <% else %>
	         <%= link_to 'Войти', new_user_session_path, class: "btn btn-default" %>
    <% end %>

<p>Find me in app/views/persons/profile.html.erb</p>
<%= link_to 'На главную страницу сайта', root_path, class: "btn btn-default" %>

app/views/repair_orders/index.html.erb
<% provide(:title, 'Orders') %>
<%= link_to 'Создать новый заказ', new_repair_order_url, class: 'btn btn-success' %>  
<%= link_to raw('<span class="glyphicon glyphicon-filter"></span>'), repair_orders_url %> 
<table class="table table-inverse table-striped">
  <thead>
    <tr>
      <th><input type="checkbox" /></th>
      <th>№ ЗАКАЗА</th>
      <th>
        <div class="dropdown">
          <a href="#" class="dropdown-toggle-js" data-toggle="dropdown">
            КРАЙНИЙ СРОК 
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><a href="#">Просроченные</a></li>
            <li><a href="#">Сначала новые</a></li>
            <li class="divider"></li>
            <li><a href="#">Сбросить</a></li>
          </ul>
        </div>
      </th>
      <th>
        <div class="dropdown">
          <a href="#" class="dropdown-toggle-js" data-toggle="dropdown">
            ПРИНЯЛ 
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <% @masters.map do |master| %>        
              <li><a href=""><%= master.name %> <div class="additional_info_in_view" ><%= master.category %></div></a></li>
            <% end -%>
          </ul>
        </div>
      </th>
      <th>
        <div class="dropdown">
          <a href="#" class="dropdown-toggle-js" data-toggle="dropdown">
            ТИП УСТРОЙСТВА 
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <% @devices.map do |device| %>        
              <li><a href=""><%= device.device_type %></a></li>
            <% end -%>
          </ul>
        </div>
      </th>
      <th>
        <div class="dropdown">
          <a href="#" class="dropdown-toggle-js" data-toggle="dropdown">
            БРЕНД
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
          
            
                    
              <li><a href=""></a></li>
            
          </ul>
        </div>
      </th>
      <th>УСТРОЙСТВО</th>
      <th>НЕИСПРАВНОСТЬ</th>
      <th>
        <div class="dropdown">
          <a href="#" class="dropdown-toggle-js" data-toggle="dropdown">
            КЛИЕНТ
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <div id="search">
              <%= form_tag(RepairOrder, :method => "get") do %>
                  <div>
                    <%= text_field_tag :search, params[:search], placeholder: "Поиск по номеру" %>
                    <button type="submit">Найти</button>
                  </div>
              <% end %>
            </div>
          </ul>
        </div>
      </th>      
      <th>ЦЕНА</th>

    </tr>
  </thead>

  <tbody>
    <% @repair_orders.each do |order| %>

      <tr>
        <td><input type="checkbox" /></td>
        <td><%= order.id %></td>
        <td><% t = sec2dhms(order.date_dead_line.to_time - Date.today.to_time) %> <%= pluralize("#{t[0]}", 'день', 'дней') %> <% order.date_dead_line %> </td>
        <td><%= @masters.find(order.master_id).name %> <br> <div class="additional_info_in_view"><%= order.created_at.strftime("%d-%m-%Y в %H:%M") %></div></td>
        <td><%= @devices.find(order.device_id).device_type %></td>
        <td><%= current_brand_name = @brands.find(@devices.find(order.device_id).brand_id).brand_name %></td>
        <td> <%= current_brand_name %> <%= @devices.find(order.device_id).model %> <br><div class="additional_info_in_view"><%= @devices.find(order.device_id).serial_number %></div></td>
        <td><%= @devices.find(order.device_id).defect %></td>
        <td><%= @claimers.find(order.claimer_id).fio %> <br> <div class="additional_info_in_view"><%= @claimers.find(order.claimer_id).phone %></div></td>        
        <td>$</td> 
        
      </tr>
   
    <% end %>
  </tbody>
</table>
<%= link_to 'Вернутся на главную', root_url, class: 'btn' %>

       <script type="text/javascript">
    $(document).ready(function(){
      $(".dropdown-toggle-js").dropdown();
    });  
    </script>
     

app/views/repair_orders/new.html.erb
<h1>Новый заказ</h1>
 
    <%= form_for @repair_order do |f| %>
     
<p>Клиент:</p>
        <%= f.fields_for :claimer do |claimer_form| %>
           
            <%= claimer_form.text_field :fio, class: "form-control", placeholder: "Ф.И.О клиента" %>
          
          <br>
           
            <%= claimer_form.text_field :phone, class: "form-control", placeholder: "Телефон" %>
          
          <br>
           
            <%= claimer_form.text_field :email, class: "form-control", placeholder: "E-mail" %>
          
          <br>
           
            <%= claimer_form.text_field :city, class: "form-control", placeholder: "Город" %>
          
          <br>
           
            <%= claimer_form.text_field :adress, class: "form-control", placeholder: "Домашний адрес" %>
          
          <br>
        <% end %>
      <br>
<p>Устройство:</p>
        <%= f.fields_for :device do |device_form| %>
           
            <%= device_form.text_field :model, class: "form-control", placeholder: "Модель устройства" %>
          
          <br>
           
            <%= device_form.text_field :serial_number, class: "form-control", placeholder: "Серийный номер" %>
          
          <br>
            <%= device_form.select :brand_id,  options_for_select(Brand.all.map{|u| [ u.brand_name, u.id ] }) %>
            <% #device_form.text_field :brand_id, class: "form-control", placeholder: "Бренд" %>
          
          <br>
           
            <%= device_form.text_field :device_type, class: "form-control", placeholder: "Тип устройства" %>
          
          <br>
           
            <%= device_form.text_field :defect, class: "form-control", placeholder: "Заявленный дефект" %>
          
          <br>
           
            <%= device_form.text_field :accessories, class: "form-control", placeholder: "Комплектность" %>
          
          <br>
           
            <%= device_form.text_field :appearences, class: "form-control", placeholder: "Внешний вид" %>
          
          <br>
        <% end %>
 
<p>непосредственно таблица repair_orders:</p>
    <p>Выбор мастера:</p>
     
      <%= select(:repair_order, :master_id, @master_options) %> <!-- выпадающее меню списка мастеров -->
      <br><br>
       
      <%= f.text_area :description, size: "15x3", class: "form-control", placeholder: "Добавить примечание к заказу" %>
     
     <br>
     
    <p>Дата покупки: <%= f.text_field :date_purchase, class: "datepicker", placeholder: "Кликните для выбора даты" %></p>
    <p>Конечный срок ремонта: <%= f.text_field :date_dead_line, class: "datepicker", placeholder: "Кликните для выбора даты" %></p>
    <p>Конец гарантии: <%= f.text_field :waranty_period, class: "datepicker", placeholder: "Кликните для выбора даты" %></p>
  <br><br>
      <%= f.submit "Создать заказ", class: "btn btn-primary"%>
    <% end %>
<br>
    <%= link_to 'Вернутся на главную', root_url%>

app/views/repair_orders/orders.html.erb
<% provide(:title, 'Orders') %>
<h1>Заказ</h1>

<table class="table table-inverse table-striped">
  <thead>
    <tr>
      <th>Имя заказчика</th>
      <th>Устройство</th>
      <th>Кто ремонтировал</th>
      <th>Описание</th>

    </tr>
  </thead>

  <tbody>
    <% @repair_orders.each do |order| %>

      <tr>
        <td><%= @claimers.find(order.claimer_id).fio %></td>
        <td><%= @devices.find(order.device_id).brand %></td>
        <td><%= @masters.find(order.master_id).name %></td>
        <td><%= order.description %></td> 
        
      </tr>
   
    <% end %>
  </tbody>
</table>

app/views/stock/index.html.erb
<ul class="nav nav-tabs" id="stock-list">
  <li class="active"><a href="#stock-show"> Наличие </a></li>
  <li><a href="#borrowed_products"> 2 </a></li>
</ul>
<div class="tab-content">
  <div class="tab-pane active" id="stock-show">
    <form class="form-horizontal">
      <table id=tblist class="table table-bordered table-striped table-hover">
        <thead>
          <tr><td><input type=text class="form-control" /></td><td><input type=text class="form-control" /></td><td><input type=text class="form-control" /></td><td><input type=text class="form-control" /></td></tr>
          <tr class='info'><td>Артикул</td><td>Наименование</td><td>наличие, ед.</td><td>цена</td></tr>
        </thead>
      <tbody>
          <tr><td>11111111111</td><td>Наименование</td><td>10</td><td>125,6</td></tr>
      </tbody>
      </table>
    </form>
  </div>
  <div class="tab-pane" id="borrowed_products" > 2 </div>
</div>


<!-- Modal -->
<div class="modal fade" id="myModals" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
     
    </div>
  </div>
</div>




<script>
  $('#stock-list a').click(function(e){
    e.preventDefault();
    $(this).tab('show')
  });
  
   $('#tblist > tbody > tr').dblclick(function(){
       $('#myModals').modal('show')
    });
  
</script>

app/views/welcome/_content.html.erb
    <p>Контент сайта</p>
    <p>Все содержимое рендерить в <code>#page-content-wrapper</code>.</p>
    <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Показать/Убрать Меню</a>

app/views/welcome/_left_menu.html.erb
        <!-- Sidebar -->
        
        <div id="sidebar-wrapper">

        
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <%= link_to "Service Manager", root_url %>
                </li>
                <li>
                    <!--<a href="#"><span class="glyphicon glyphicon-inbox"></span> &ensp; Заказы</a>-->
                    <%= link_to raw('<span class="glyphicon glyphicon-inbox"></span>&ensp; Заказы'), repair_orders_url %>
                </li>
                <li>
                    <a href="#"><span class="glyphicon glyphicon-usd"></span> &ensp; Кассы</a>
                </li>
                <li>
                    <a href="#"><span class="glyphicon glyphicon-shopping-cart"></span> &ensp; Магазин</a>
                </li>
                <li>

                    <!--<a href="#"><span class="glyphicon glyphicon-barcode"></span> &ensp; Склад</a>-->
                    <%= link_to raw('<span class="glyphicon glyphicon-inbox"></span>&ensp; Склад'), stock_index_url %>
                </li>
                <li>
                    <a href="#"><span class="glyphicon glyphicon-user"></span> &ensp; Клиенты</a>
                </li>
                <li>
                    <a href="#"><span class="glyphicon glyphicon-tasks"></span> &ensp; Отчеты</a>
                </li>
                <li>
                    <!--<a href="#"><span class="glyphicon glyphicon-cog"></span> &ensp; Настройки</a>-->
                    <%= link_to raw('<span class="glyphicon glyphicon-cog"></span>&ensp; Настройки'), new_master_url %>
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

app/views/welcome/_top.html.erb
<!-- Page Content -->
        <div id="page-content-wrapper">

            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <p class="notice"><%= notice %></p>
					              <p class="alert"><%= alert %></p>

app/views/welcome/_top_menu.html.erb
<div class="top-side-menu">
	<nav class="user-menu">
   
        <% if user_signed_in? %>
	        <span>Здравствуйте, <span class="email-style"><%= current_user.email %></span></span>
	        <%= link_to 'Выйти', destroy_user_session_path, :method => :delete %>
	    <% else %>
	         <%= link_to 'Войти', new_user_session_path %>
        <% end %>
	</nav>
</div>

app/views/welcome/index.html.erb
<% provide(:title, 'Welcome') %>  				

<%= render partial: "content" %>



  